name = "paineldiario"
compatibility_date = "2026-07-13"
main = "worker.js"

[assets]
directory = "./"
binding = "ASSETS"
not_found_handling = "404-page"

[[kv_namespaces]]
binding = "PAINEL_KV"
id = "76d26726c3d044f38339afed3b9c1330"
